In [ ]:
print("Welcome")

Welcome

Upload Your File

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving table6_2026_04.csv to table6_2026_04.csv

Create Data frame

In [ ]:
import pandas as pd

df = pd.read_csv("table6_2026_04.csv")

print(df.shape)
# verify
df.head()

(1981, 18)

,reporting_month,ministry,sector,sl_no,project_name,agency,project_code,legacy_ocms_code,pmgid,state,approval_start_date,revised_start_date,target_doc,revised_doc,original_cost_cr,revised_cost_cr,cumulative_expenditure_cr,physical_progress_pct
0,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,1,Construction of New Domestic Terminal Building...,Airport Authority of India [AAI],612786,N04000106,NaN,Andhra Pradesh,03/2023,01/2024,01/2026,07/2026,265.91,265.91,129.07,65.00
1,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,2,Construction of New Integrated Terminal Buildi...,Airport Authority of India [AAI],701107,N04000091,4353.0,Andhra Pradesh,06/2020,09/2020,09/2022,10/2026,611.80,611.80,523.14,87.20
2,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,3,Construction of New Domestic Terminal Building...,Airport Authority of India [AAI],701121,N04000103,NaN,Andhra Pradesh,12/2022,08/2023,08/2025,06/2026,347.15,347.15,170.79,90.00
3,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,4,Guwahati Airport New Integrated Terminal Build...,Adani Airport Holdings Limited,706724,N04000083,9925.0,Assam,12/2016,03/2018,03/2025,06/2026,1712.00,2520.00,2627.39,98.00
4,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,5,Development of New Civil Enclave at Bihta,Airport Authority of India [AAI],612183,NaN,9918.0,Bihar,08/2024,04/2025,03/2027,NaN,1413.00,1413.00,7.64,1.28

In [ ]:
import numpy as np

Derived Features : Placeholders| Do not run

In [ ]:
financial_progress_pct = (
    cumulative_expenditure_cr / original_cost_cr
) * 100

progress_gap = (
    financial_progress_pct - physical_progress_pct
)

start_delay_months = (
    revised_start_date - approval_start_date
).days / 30.44

Cost Overrun Features

Verify Data First

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1981 entries, 0 to 1980
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   reporting_month            1981 non-null   object
 1   ministry                   1981 non-null   object
 2   sector                     1981 non-null   object
 3   sl_no                      1981 non-null   int64
 4   project_name               1981 non-null   object
 5   agency                     1981 non-null   object
 6   project_code               1981 non-null   int64
 7   legacy_ocms_code           1184 non-null   object
 8   pmgid                      1213 non-null   float64
 9   state                      1981 non-null   object
 10  approval_start_date        1970 non-null   datetime64[ns]
 11  revised_start_date         1981 non-null   datetime64[ns]
 12  target_doc                 1981 non-null   object
 13  revised_doc                1627 non-null   object
 14  original_cost_cr           1981 non-null   float64
 15  revised_cost_cr            1981 non-null   float64
 16  cumulative_expenditure_cr  1981 non-null   float64
 17  physical_progress_pct      1981 non-null   float64
 18  cost_overrun               1981 non-null   int64
 19  financial_progress_pct     1981 non-null   float64
 20  progress_gap               1981 non-null   float64
 21  start_delay_months         1970 non-null   float64
dtypes: datetime64[ns](2), float64(8), int64(3), object(9)
memory usage: 340.6+ KB

In [28]:
df.head()

,reporting_month,ministry,sector,sl_no,project_name,agency,project_code,legacy_ocms_code,pmgid,state,...,target_doc,revised_doc,original_cost_cr,revised_cost_cr,cumulative_expenditure_cr,physical_progress_pct,cost_overrun,financial_progress_pct,progress_gap,start_delay_months
0,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,1,Construction of New Domestic Terminal Building...,Airport Authority of India [AAI],612786,N04000106,NaN,Andhra Pradesh,...,01/2026,07/2026,265.91,265.91,129.07,65.00,0,48.538979,-16.461021,10.0
1,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,2,Construction of New Integrated Terminal Buildi...,Airport Authority of India [AAI],701107,N04000091,4353.0,Andhra Pradesh,...,09/2022,10/2026,611.80,611.80,523.14,87.20,0,85.508336,-1.691664,3.0
2,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,3,Construction of New Domestic Terminal Building...,Airport Authority of India [AAI],701121,N04000103,NaN,Andhra Pradesh,...,08/2025,06/2026,347.15,347.15,170.79,90.00,0,49.197753,-40.802247,8.0
3,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,4,Guwahati Airport New Integrated Terminal Build...,Adani Airport Holdings Limited,706724,N04000083,9925.0,Assam,...,03/2025,06/2026,1712.00,2520.00,2627.39,98.00,1,153.469042,55.469042,15.0
4,2026-04,Ministry of Civil Aviation,Aviation & Aviation Infrastructure,5,Development of New Civil Enclave at Bihta,Airport Authority of India [AAI],612183,NaN,9918.0,Bihar,...,03/2027,NaN,1413.00,1413.00,7.64,1.28,0,0.540694,-0.739306,8.0

In [ ]:
df.isna().sum()

reporting_month                0
ministry                       0
sector                         0
sl_no                          0
project_name                   0
agency                         0
project_code                   0
legacy_ocms_code             797
pmgid                        768
state                          0
approval_start_date           11
revised_start_date             0
target_doc                     0
revised_doc                  354
original_cost_cr               0
revised_cost_cr                0
cumulative_expenditure_cr      0
physical_progress_pct          0
dtype: int64

Revised Cost overrun experiment

In [ ]:
df["cost_overrun"] = (
    df["revised_cost_cr"] > df["original_cost_cr"]
).astype(int)

print(df["cost_overrun"].value_counts())

cost_overrun
0    1439
1     542
Name: count, dtype: int64

Feature Engineering

In [ ]:
cost_features = [
    "ministry",
    "sector",
    "agency",
    "state",
    "original_cost_cr",
    "cumulative_expenditure_cr",
    "physical_progress_pct",
    "financial_progress_pct",
    "progress_gap",
    "start_delay_months"
]

target = "cost_overrun"

Add them into Data Frame

In [ ]:
financial_progress_pct = (
    cumulative_expenditure_cr / original_cost_cr
) * 100

progress_gap = (
    financial_progress_pct - physical_progress_pct
)

start_delay_months = (
    revised_start_date - approval_start_date
).days / 30.44

Run This

In [ ]:

# 1. Financial progress
df["financial_progress_pct"] = (
    df["cumulative_expenditure_cr"]
    / df["original_cost_cr"].replace(0, np.nan)
) * 100

In [ ]:
# 2. Progress gap
df["progress_gap"] = (
    df["financial_progress_pct"]
    - df["physical_progress_pct"]
)

Clean the date time

In [ ]:
df["approval_start_date"] = pd.to_datetime(
    df["approval_start_date"], format="%m/%Y", errors="coerce"
)

df["revised_start_date"] = pd.to_datetime(
    df["revised_start_date"], format="%m/%Y", errors="coerce"
)

In [ ]:
# 3. Start delay in months
df["start_delay_months"] = (
    (df["revised_start_date"].dt.year -
     df["approval_start_date"].dt.year) * 12
    +
    (df["revised_start_date"].dt.month -
     df["approval_start_date"].dt.month)
)

Check Null values for Features

In [30]:
print(df[cost_features].isna().sum())

ministry                      0
sector                        0
agency                        0
state                         0
original_cost_cr              0
cumulative_expenditure_cr     0
physical_progress_pct         0
financial_progress_pct        0
progress_gap                  0
start_delay_months           11
dtype: int64

# Convert dates

In [31]:
df["approval_start_date"] = pd.to_datetime(
    df["approval_start_date"],
    format="%m/%Y",
    errors="coerce"
)

In [32]:
df["revised_start_date"] = pd.to_datetime(
    df["revised_start_date"],
    format="%m/%Y",
    errors="coerce"
)

Convert String to Numeric values

In [33]:
# Make physical progress numeric
df["physical_progress_pct"] = pd.to_numeric(
    df["physical_progress_pct"],
    errors="coerce"
)

# Prepare X and Y

In [34]:
X = df[cost_features]
y = df["cost_overrun"]

prepare  train/test split

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (1584, 10)
X_test : (397, 10)
y_train: (1584,)
y_test : (397,)

 Define Numerical and categorical columns

In [37]:
categorical_features = [
    "ministry",
    "sector",
    "agency",
    "state"
]

numeric_features = [
    "original_cost_cr",
    "cumulative_expenditure_cr",
    "physical_progress_pct",
    "financial_progress_pct",
    "progress_gap",
    "start_delay_months"
]

# Preprocessing pipeline

Import requirements

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

Now Convert

In [39]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

Create Preprocessor

In [40]:
preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])
print("done")

done

Create Model : Logistic Regression

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

cost_model = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=1000
    ))
])

# Train Model

In [42]:
cost_model.fit(X_train, y_train)

print("Cost Overrun Model trained successfully.")

Cost Overrun Model trained successfully.

Prediction Checking

In [43]:
y_pred = cost_model.predict(X_test)

y_prob = cost_model.predict_proba(X_test)[:, 1]

print(y_pred[:10])
print(y_prob[:10])

[0 0 1 0 0 0 0 0 1 0]
[0.36937314 0.49377837 0.52575053 0.02486602 0.1652818  0.07039249
 0.27811489 0.08392131 0.94461637 0.05187198]

Model evaluation

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("ROC-AUC:")
print(roc_auc_score(y_test, y_prob))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.75      0.82       288
           1       0.54      0.77      0.63       109

    accuracy                           0.76       397
   macro avg       0.72      0.76      0.73       397
weighted avg       0.80      0.76      0.77       397

ROC-AUC:
0.8536888379204893
Confusion Matrix:
[[216  72]
 [ 25  84]]

# Model Ready to Save

In [47]:
import joblib

joblib.dump(cost_model, "cost_overrun_model_v1.pkl")

print("Model saved successfully.")

Model saved successfully.

# Download Model Weight

In [48]:
from google.colab import files

files.download("cost_overrun_model_v1.pkl")